
stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Budowanie aplikacji..."

job_test:
  stage: test
  script:
    - echo "Uruchamianie testów..."

job_deploy:
  stage: deploy
  script:
    - echo "Wdrażanie aplikacji..."
